### ISSUE TITLE
Planed features

### ISSUE THREAD

**Issue by badwolfie** [BadWolfie/simple-text#1]
#### Milestones for v1.0:
- [x] Syntax highlighting
- [x] Change style scheme
- [x] Change text font and size
- [x] Change syntax while editing
- [x] Word completion
- [x] Brace completion
- [x] Re-open last tab
- [x] Building (using make) _Very primitive stage but it works!_
- [x] Searching
- [x] Embeeded terminal + Terminal resizing
- [x] Drag n' drop support
- [x] Translations
#### Milestones for v1.1:
- [ ] Minimap
#### Milestones for v1.2:
- [ ] Code completion for C/C++

**_More to be defined...**_
